### ISSUE TITLE
Code does not work with Dropbox links

### ISSUE THREAD

**Issue by sizhky** [fastai/fastdownload#16]
What is the reason behind this? Is there a way to get around this?

**Comment by GenevieveBuckley** [comment]
Could you post the example code you used to try it?

**Comment by GenevieveBuckley** [comment]
Circling back to this question, you might like to try it again and see what happens:

In the terminal, in your python environment:
1. `pip uninstall fastdownload`
2. `pip install "git+https://github.com/GenevieveBuckley/fastdownload/@fmod-exists-error"`
3. Start `python` or `ipython`/`jupyter notebook` (whatever your preferred method of using python is)
4. From python try this, replacing the dropbox link with your own (see important points below): 
    ```python
    from fastdownload import FastDownload
    d = FastDownload()
    path = d.get('https://...my-dropbox-link... .zip?dl=1')
    ```

**Important point 1:** You need to add `?dl=1` on the end of your dropbox link, it goes straight after the `.zip` or `.tar` part of the filename. It's a flag (1 means True, 0 means False), so `?dl=1` means download the file automatically, and `?dl=0` means don't download the file automatically just show the dropbox webpage for that file. This is what happens when you paste dropbox links with those endings directly into your web browser. See [How to force a shared Dropbox link to download or render](https://help.dropbox.com/files-folders/share/force-download) for details.

**Important point 2:** Ideally, your file should be already compressed, eg: `.zip`, `.tar`, `.gtar`, `.btar`, or `.xtar`. See [this page](https://docs.python.org/3/library/shutil.html#shutil.get_archive_formats) for an explanation of those file formats. If your file isn't already zipped/tarred/compressed, you can still use `fastdownload`, you'll just need to use the download function: `path = d.download("https://...")` instead of `path = d.get("https://..."`. That will put your file into a folder called `archive` on your local computer (eg: `/home/username/.fastdownload/archive/` instead of `/home/username/.fastdownload/data/`, or whatever your local equivalent is).

Let me know if that helps.

**Comment by sizhky** [comment]
I'll wait this gets merged with the main branch. For now, I am uploading to AWS

**Comment by jph00** [comment]
IIUC this is working now - so closing. Please at-mention me if you have a reproducible non-working example.
